// <auto-generated />
using System;
using Labo_Agence_Voyage.DAL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labo_Agence_Voyage.DAL.Migrations
{
    [DbContext(typeof(AgenceVoyageDbContext))]
    [Migration("20251220110656_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labo_Agence_Voyage.Domain.Entities.Activiter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Prix")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id")
                        .HasName("PK_Activites");

                    b.HasIndex("DestinationId");

                    b.ToTable("Activites", (string)null);
                });

            modelBuilder.Entity("Labo_Agence_Voyage.Domain.Entities.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Destinations");

                    b.HasIndex("Nom", "Pays")
                        .IsUnique()
                        .HasDatabaseName("UK_Destination_Nom_Pays");

                    b.ToTable("Destinations", (string)null);
                });

            modelBuilder.Entity("Labo_Agence_Voyage.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Reservations");

                    b.HasIndex("ReservationId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("Labo_Agence_Voyage.Domain.Entities.Activiter", b =>
                {
                    b.HasOne("Labo_Agence_Voyage.Domain.Entities.Destination", "Destination")
                        .WithMany("Activites")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Labo_Agence_Voyage.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Labo_Agence_Voyage.Domain.Entities.Destination", "Destination")
                        .WithMany("Reservations")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Labo_Agence_Voyage.Domain.Entities.Destination", b =>
                {
                    b.Navigation("Activites");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
